### ISSUE TITLE
Confusion about `*-for-mac*`-files

### ISSUE THREAD

**Issue by gcomte** [fluidex/orchestra#28]
Commit https://github.com/fluidex/orchestra/commit/74deffb697bcea73e3cfc20a7632d47611ad56bf introduced a new file `envoy-for-mac.yaml` alongside the file `envoy.yaml`.

On top of that, a new file `docker/docker-compose-for-mac.yaml` was introduced alongside the file `docker/docker-compose.yaml`. Interestingly enough, these two files are identical. Is there a need for two identical files? Or should there be a difference between the files, e.g. that `docker/docker-compose.yaml` should refer to `./envoy.yaml` instead of `./envoy-for-mac.yaml` [which it does now](https://github.com/fluidex/orchestra/blob/master/docker/docker-compose.yaml#L62)?

I don't really understand what `mac` stands for, but I assume it's meant to mean [a computer from Apple](https://en.wikipedia.org/wiki/Macintosh). For that reason, since I myself develop on a Linux distro, I personally continued to use the file `envoy.yaml` instead of `envoy-for-mac.yaml`. However, there seems to be a problem with the docker networking (which unfortunately I don't understand very well):

I had to change the lines [77](https://github.com/fluidex/orchestra/blob/master/docker/envoy.yaml#L77), [96](https://github.com/fluidex/orchestra/blob/master/docker/envoy.yaml#L96) and [116](https://github.com/fluidex/orchestra/blob/master/docker/envoy.yaml#L116) from `0.0.0.0` to `host.docker.internal` on my machine for the JS tests to be able to communicate with envoy (particularly the test [print-orders.js](https://github.com/fluidex/dingir-exchange/blob/master/examples/js/print_orders.ts)), but ironically, these lines are the only difference between `envoy.yaml` and `envoy-for-mac.yaml`. So changing these values from `0.0.0.0` to `host.docker.internal` makes the file `envoy.yaml` identical to the file `envoy-for-mac.yaml`.

So there seem to be a couple of things wrong here, or I just completely misunderstand the semantics behind these files and am therefore making mistakes (or likely, a combination of both).

**Comment by HAOYUatHZ** [comment]
Yes, `mac` means Apple's Darwin OS.

1. I agree `docker-compose.yaml` should link to `envoy.yaml`.
2. Maybe the `envoy.yaml` use `0.0.0.0` incorrectly. But because we were using `envoy-for-mac.yaml`, we didn't identify/realize the problem?

@silathdiir Can you double check?

**Comment by HAOYUatHZ** [comment]
Hi @gcomte maybe this issue can be closed by https://github.com/fluidex/orchestra/pull/29?

**Comment by gcomte** [comment]
Hey @HAOYUatHZ 

Thanks for the quick action! This fixes my problem so yes, the issue could be closed, but I just wanted to point out one more time, that given the recent changes, the file `envoy.yaml` is now _identical_ to the file `envoy-for-mac.yaml`, which in a sense makes the files `docker/docker-compose.yaml` and `docker/docker-compose-for-mac.yaml` identical too, because they only differ in pointing to a different `envoy.yaml` file, which are themselves identical, as described above.

**Comment by HAOYUatHZ** [comment]
> Hey @HAOYUatHZ
> 
> Thanks for the quick action! This fixes my problem so yes, the issue could be closed, but I just wanted to point out one more time, that given the recent changes, the file `envoy.yaml` is now _identical_ to the file `envoy-for-mac.yaml`, which in a sense makes the files `docker/docker-compose.yaml` and `docker/docker-compose-for-mac.yaml` identical too, because they only differ in pointing to a different `envoy.yaml` file, which are themselves identical, as described above.

yeah there seems no need for "-for-mac-" files.  we used it for some legacy issue.

**Comment by HAOYUatHZ** [comment]
> Hey @HAOYUatHZ
> 
> Thanks for the quick action! This fixes my problem so yes, the issue could be closed, but I just wanted to point out one more time, that given the recent changes, the file `envoy.yaml` is now _identical_ to the file `envoy-for-mac.yaml`, which in a sense makes the files `docker/docker-compose.yaml` and `docker/docker-compose-for-mac.yaml` identical too, because they only differ in pointing to a different `envoy.yaml` file, which are themselves identical, as described above.

yeah there seems no need for "-for-mac-" files.  we used it for some legacy issues. I will dig into it. and if it's safe to remove them I will remove them.

**Comment by HAOYUatHZ** [comment]
"-for-mac-" files are introduced by https://github.com/fluidex/orchestra/pull/15/files. But it's true that they are identical with those non-"-for-mac-" files. Seems we should remove them.
